name: Check Vulnerabilities

on:
  push:
    branches: [ main ]

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run vulnerability check script
      run: bash .github/scripts/vulnerability-check.sh
      
    - name: Archive vulnerability data
      uses: actions/upload-artifact@v2
      with:
        name: vulnerabilities
        path: .github/scripts/vulnerabilities.csv
